string actionName                 
string actionParam1               
string actionParam2 
string actionParam3 
string actionParam4 
string actionParam5 
string actionConstraint           
int32 actionID                    
--- 
int32 result
int32 SUCCESS = 1
int32 FAIL = 0
