move_arms:
  ros_msg: MoveArmAction
  input:
    - name: initial_state
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: target_state
      type: std_msgs/float64[]
      description: end-effector pose / robot joint state (goal)
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position