# actions
move_arm:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
    - name: currentJointState
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: jointGoal
      type: sensor_msgs/JointState
      description: target joint state (goal)
      required: false
    - name: poseGoal
      type: geometry_msgs/Pose
      description: end-effector pose (goal)
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
  output:
    - name: jointTrajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position
carry_object:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
      required: false
    - name: carryLocation
      type: int32
      description: top,left,right,front
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
    - name: target_object
      type: std_msgs/String
      description: object name
  output:
    - name: jointTrajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position
pouring_object:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
      required: false
    - name: toolName
      type: string
      description: tool name
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
    - name: target_object
      type: std_msgs/String
      description: object name
  output:
    - name: jointTrajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position
rotate_object:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
      required: false
    - name: targetPart
      type: geometry_msgs/Vector3
      description: center of the part
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
    - name: target_object
      type: std_msgs/String
      description: object name
  output:
    - name: jointTrajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position
grasp_object:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
    - name: currentJointState
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: target_object
      type: std_msgs/String
      description: object name
      required: true
    - name: obstacles
      type: std_msgs/String[]
      description: obstacle names
      required: false
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory), arm+gripper
  constraints:
    - hardware: arm gripper
      controller: position
approach_to_object:
  input:
    - name: targetBody
      type: int32
      description: target body of the robot(the type of the body)
      required: true
    - name: currentJointState
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: targetObject
      type: std_msgs/String
      description: object name
      required: true
    - name: obstacles
      type: std_msgs/String[]
      description: obstacle names
      required: false
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory), arm+gripper
  constraints:
    - hardware: arm gripper
      controller: position
gripper_open_close:
  input:
    - name: graspPose
      type: float32[]
      description: eigen grasp
      required: true
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory), gripper
  constraints:
    - hardware: gripper
      controller: position
push_object:
  ros_msg: PushObjectAction
  ros_service: /actionlib/push_object
  input:
    - name: initial_state
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: target_state
      type: std_msgs/float64[]
      description: goal pose of the object
      required: true
    - name: target_object
      type: std_msgs/float64[]
      description: object information
      required: true
    - name: obstacles
      type: vision_msgs/BoundingBox3D[]
      description: obstacle bounding box
      required: false
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position
pull_object:
  ros_msg: MoveArmAction
  ros_service: /actionlib/pull_object
  input:
    - name: unknown
      type: unknown
      description: unknown
      required: true
    - name: unknown
      type: unknown
      description: unknown
      required: false
  output:
    - name: unknown
      type: unknown
      description: unknown
  constraints:
    - hardware: unknown
      controller: unknown
set_gripper:
  ros_msg: SetGripperAction
  ros_service: /actionlib/set_gripper
  input:
    - name: initial_state
      type: sensor_msgs/JointState
      description: robot state(start)
      required: true
    - name: target_state
      type: std_msgs/String
      description: primitive pose
      required: true
  output:
    - name: joint_trajectory
      type: trajectory_msgs/JointTrajectory
      description: path(joint trajectory)
  constraints:
    - hardware: arm
      controller: position

